#!/usr/bin/env node

const fs = require('fs')
const findPaths = require('./lib/findPaths')
const PageHTML = require('./lib/PageHTML')
const parseHTML = require('./lib/parseHTML')
const validateConfig = require('./lib/validateConfig')
const config = require('./config')

validateConfig(config)

const {
  domain,
  scripts,
  stylesheets,
  publicDir,
  pages,
} = config

/**
 * @name main
 *
 * @synopsis
 * ```coffeescript [specscript]
 * main() -> Promise<>
 * ```
 */
async function main() {
  const paths = await findPaths(`${__dirname}/${publicDir}`, {
    ignore: ['*.css', '*.js'],
  })

  for (const path of paths) {
    const pageFilepath = path.replace(`${__dirname}/${publicDir}`, '')
    const content = await fs.promises.readFile(path)
    const page = pages.find(page => page.filepath == pageFilepath)

    if (page == null) {
      console.error(content)
      throw new Error(`page not found in config: ${pageFilepath}`)
    }

    const { title, description, url } = page

    const $ = parseHTML(content)
    const bodyHTML = $('body').html().trim()

    console.log('Updating page', path.replace(process.env.HOME, '~'))

    await fs.promises.writeFile(path, PageHTML({
      title,
      description,
      url: `https://${domain}${url}`,
      scripts,
      stylesheets,
      bodyHTML,
    }))
  }

}

main()
